Vagrant.configure("2") do |config|
    config.vm.box = "eurolinux-vagrant/centos-stream-9"

    config.vm.network "private_network", ip: "192.168.56.17"
    config.vm.network "public_network" , bridge: "en0: Ethernet"

    # Make the default /vagrant folder use NFS (bidirectional)
    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    
    config.vm.synced_folder "scripts", "/opt/scripts", type: "nfs"

    config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = 1024
    end
end